name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: inspect 2
        run: |
          ls -al
          echo Qui soc? $(whoami)
          pwd
          nodeversion=$(node -v)
          echo $nodeversion
          docker version
          docker compose version