name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: inspect
        run: |
          ls -al
          echo Qui soc? ${whoami}
          pwd
          echo Nose version? ${node -v}
          docker version
          docker compose version